apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pvc-template
objects:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
  volumeMode: Filesystem